name: Build and push to docker hub

on:
  push:
    branches:
      - master

env:
  IMAGE: pnsnk2410/mlops

jobs:
  build-publish:
    name: Build Publish to DockerHub
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          make build
          
      - name: Push Docker Image
        run: |
          make push